# Generated by Django 3.2.16 on 2022-12-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='name',
        ),
    ]
