# Generated by Django 3.2.16 on 2023-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_title_journal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('JPY', '¥'), ('GBP', '£'), ('CHF', 'CHF')], default='EUR', max_length=3),
            preserve_default=False,
        ),
    ]
