# Generated by Django 3.2.16 on 2023-01-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('¥', 'JPY'), ('£', 'GBP'), ('CHF', 'CHF')], max_length=3),
        ),
    ]
