# Generated by Django 3.2.16 on 2023-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_journal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
