# Generated by Django 3.2.16 on 2023-01-12 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_trade_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
