# Generated by Django 3.2.16 on 2023-01-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_journal_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
