# Generated by Django 3.2.18 on 2023-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20230112_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='comments',
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
